### ISSUE TITLE
Action tracking

### ISSUE THREAD

**Issue by jingyuyao** [jingyuyao/tactical-adventure#178]
We can generalize the actions that affects the game in a more formal way. Currently, the state and model objects invokes functions that changes the world. The result of these functions are not documented. There is no way to easily track and see what happened.

Proposal:
Create a system where all the actions that affects the world happen in one place, in sequence and logged. World, WorldState and model classes should produce action that can be executed by the action system. The script can also generate actions. Script should be run on client for single player and on server for multi-player.

Result:
- Enables auditing of actions
- Easier to debug as all modification to game state is logged
- Enables multi-player as all action can be repeated, serialized and distributed in a client-server method
- Even faster saving as we only need to save the actions instead of the whole world state -- Nah, there is no point
- This separates actions from the state transitions. Right now the state package is doing too much. Its maintaining the user state flow as well as performing all the logic on the world.

Requirements:
- [ ] An action must be able to check current world state for validity
- [ ] An action must be able to change a valid world state in a reproduce-able manner (i.e. applying the same action on the same world state multiple times should have the same effect)
- [ ] A list of actions must be logged per level
- [ ] There must be a system that applies a single or a list of actions to the world state
- [ ] Everything that changes the world state must be an action
- Actions:
  - [ ] Moving a ship
  - [ ] Removing a ship
  - [ ] Activating a ship
  - [ ] Deactiving a ship
  - [ ] Performing a battle (applying weapon to a target area, should include damage components and generate removing ship actions if necessary?)
  - [ ] Using a consumable
  - [ ] Ending a turn
 

Problems:
- What kind of data does an action save? For example, do we save the cell and ship when spawning? How do we link the cell and ship in the action with the world?
- We will probably need identify object by some sort of ID. Then save the id of the objects in actions so we can reference them
- Should logic be in actions? Yes, actions should "operate" on world and world state.
- Should action be used as events? No, events should wrap actions
- This is a very large endeavor. Do we have to do this right now? Yes, we do need a more formal way of designing changes to the world. Logic is all over the place right now and everything is hard to being kept track of.
